allowBuilds:
  '@compodoc/compodoc': true
  '@parcel/watcher': false
  '@swc/core': false
  esbuild: true
  lefthook: true
  lmdb: false
  msgpackr-extract: false
  nx: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@compodoc/compodoc'
  - unrs-resolver
  - esbuild
  - lefthook
  - lmdb
  - nx
