[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["Ahryman40k"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.3.0", features = [] }
tauri-typegen = "0.5.0"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.6.2", features = ["tray-icon"] }
tauri-plugin-log = "2"
tauri-plugin-single-instance = "2"
tokio = { version =  "1.0.0", features = ["full"] }
thiserror = "2.0.18"
log = "0.4.29"
futures = "0.3.32"
specta        = { version = "2.0.0-rc.22", features = ["derive"] }
tauri-specta  = { version = "2.0.0-rc.21", features = ["derive", "typescript"] }

# Linux only
[target.'cfg(target_os = "linux")'.dependencies]
zbus = { version = "5.12.0", features = ["tokio"] }

# Windows only
[target.'cfg(target_os = "windows")'.dependencies]
reqwest = { version = "0.12", features = ["json"] }
