name: CI
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm ci
      - run: npm nx build synapse-copycat